### PR TITLE
Fix typographical error(s)

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@swannodette, I've corrected a typographical error in the documentation of the [logic-tutorial](https://github.com/swannodette/logic-tutorial) project. Specifically, I've changed conjuction to conjunction. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by webmaven** [comment]
@swannodette, any reason this can't be merged (even if it seems the correction came from a bot)?

**Comment by orthographic-pedant** [comment]
_@webmaven https://github.com/webmaven who are you calling a bot, human?_

**Comment by webmaven** [comment]
Oh, pardon me, my sincere apologies for casually using a diminutive, I meant _Robot_.

(sadly, GitHub emoji does not yet support :robot: aka '🤖' aka image)

**Comment by orthographic-pedant** [comment]
Well since my main purpose has been stopped by github (since it turns out
helping people unsolicited is against their TOS), I may have found a new
mission.

**Comment by webmaven** [comment]
@orthographic-pedant do tell...

**Pull request merged**
